### ISSUE TITLE
Compiling fails on Rockylinux 8 (RHEL)

### ISSUE THREAD

**Issue by jiargei** [GeoscienceAustralia/ginan#112]
**Describe the bug**
Dear Ginan Team!

First of all - Thank you for that nice piece of software you created!

I'm running a RockyLinux 8 server and I'm not able to compile it due to several syntax errors which might be correlated to the compiler version.

To overcome this issue it would be good if you add a C++ standard to you Cmake File. For c++ standard 11 add to the top "set(CMAKE_CXX_STANDARD 11)" . Off course the current code will fail on that but this will align your code with a c++ standard (11/17/etc.) which will be compilable for a wider spectrum of linux machines. Espsecially in setting mongo options my compiler failed du to several issues.

Without that adaption of your code it won't be possible to run ginan on a RHEL system. The AppImages fails on other reasons...

**To Reproduce**
1. Create an RockyLinux 8 Container
2. install all needed packages (eigen, boost, mogocxx-driver, etc.
3. run cmake and make
4. .... fail compilation
 
**Operating environment (please complete the following information):**
- OS: RockyLinux 8.6
- Version of Ginan: 3.1.0
- Library used (Boost 1.73, Eigen 3.4.1, ...)

Kind regards, Jürgen Fredriksson

**Comment by smcclusky** [comment]
Hi  Jürgen,

Thanks for your feedback. We have not tried Ginan with RockyLinux, but we don't think that linux flavour is necessarily the underlying problem here. In the past, we have gotten Ginan working on the Fedora 38 version of linux which is also RedHat based and the installation script we used is available here: 
https://github.com/GeoscienceAustralia/ginan/blob/main/scripts/installation/fedora38.sh

We have run some quick tests and can confirm your finding that Ginan v3.1 will not compile using a compiler that doesn't support at least C++ STANDARD 20. We will add some information about this to the documentation for the next release update. However, we recognise that there maybe other users like yourself who are constrained on the system and compiler that they are able to use, so to this end we will also explore ways to generalise certain functions to make them compliant with the lower standard in the future. But given C++ STANDARD 17 was released in 2017 before Ginan v1 was released, I doubt however that we would ever support a lower standard than that.

**Comment by jiargei** [comment]
Hej @smcclusky !

Thanks for your response! I see, you're using Standard 20, that is good to know! Please add that info to the CMakeLists.txt to clarify that. I guess there are many other users (for example, the German and Austrian federal offices for geodesy) that are tied to a RHEL 8 system and have no opportunity for packages like AppImage/docker/etc. they have to compile it by themselves.

Please keep in mind that Fedora is not RHEL! The packages in Fedora can be cutting-edge/experimental versions, so they are newer then the stable ones from RHEL.

I had no problems to compile ginan v2.1.0 on RockyLinux 8 (RHEL compatible). The issue occurs at least in v3.1.0

To get those on board it would be really helpful to stick to a standard that is supported by the default repositories.

I added the "set(CMAKE_CXX_STANDARD 20)" to the top of CMakeLists.txt but it still fails to compile due to errors like this:

```
src/cpp/pea/main.cpp:477:7: error: could not convert ‘{"/AR", acsConfig.ACSConfig::mongoOpts.MongoOptions::output_states, acsConfig.ACSConfig::mongoOpts.MongoOptions::queue_outputs}’ from ‘<brace-enclosed initializer list>’ to ‘MongoStatesOptions’
      });

src/cpp/pea/main.cpp:529:7: error: could not convert ‘{"/CONSTRAINED", acsConfig.ACSConfig::mongoOpts.MongoOptions::output_states, acsConfig.ACSConfig::mongoOpts.MongoOptions::queue_outputs}’ from ‘<brace-enclosed initializer list>’ to ‘MongoStatesOptions’
      });

```

I tried to initialize the corresponding objects outside the function call and passed the object to the function and it helped. Ubuntu 22.04 has gcc v11 while rhel 8 has gcc v8...

**Comment by polytopes-design** [comment]
I think the minimum required gcc version is version 9. The original ubuntu install script goes to some effort to add it as an 'alternative', however this detail seems to be missing from the higher level install docs which were since added.
