### ISSUE TITLE
How can NMEA be fed as the realtime stream in satellite_data?

### ISSUE THREAD

**Issue by javadtaghia** [GeoscienceAustralia/ginan#84]
Thanks for the great product. 
I have a question regarding live corrections that can be done using Ginan.

Can Ginan be used to use the live NTRIP published at [ntrip.data.gnss.ga.gov.au](http://ntrip.data.gnss.ga.gov.au/) as gnss_observation and improve the input from a GNSS receiver that sends NMEA?

If yes, how can it be configured to accept real time data from a GNSS receiver? 
If the receiver sends in NMEA, is it acceptable to Ginan?

I found an example r_ppp_example.yaml
(https://github.com/GeoscienceAustralia/ginan/blob/main/exampleConfigs/rt_ppp_example.yaml)

satellite data still is coming from [ntrip.data.gnss.ga.gov.au](http://ntrip.data.gnss.ga.gov.au/) and have offset APC.

How can I change the satellite_data to look into a GNSS receiver locally connected to a USB sending NMEA?

**Comment by ronaldmaj** [comment]
Hi [javadtaghia](https://github.com/javadtaghia),

Thanks for your question. Ginan requires the raw ranging observation data in order to process positions. This can come from RINEX data files or RTCM streams but those observations are critical. If you are using Ginan with a correction stream, you will also need to connect to raw observations.

NMEA data are post-processed and provide a solution to observations that were used previously, i.e. they provide positions (along with datestamps and other information) after processing observation data.
Therefore, NMEA data are not raw ranging observations and generally cannot be used to carry out the type of analysis you are looking at. You can process real-time data from a GNSS receiver, but that receiver will need to output the raw observations which you can feed into Ginan.
This may be useful information as well: https://gis.stackexchange.com/questions/274965/postprocessing-with-nmea-data-if-no-rinex-data-is-available

Hope that helps. If you have any further questions or queries, please let us know :)
