### ISSUE TITLE
Incorrect number of seconds in a week

### ISSUE THREAD

**Issue by Pikamander2** [GeoscienceAustralia/ginan#88]
Hi there, I used a code search and found an incorrect number of seconds in a week (608400 instead of 604800) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/GeoscienceAustralia/ginan/blob/0f263270daa1d5234d1194d3bc314cf3dca85f38/src/cpp/common/mqtt.cpp#L36

**Comment by seballgeyer** [comment]
Hello, 

Thank you for your attention to detail in spotting the incorrect number of seconds in a week in the mqtt.cpp file.

While this error was present, it's important to clarify that the mqtt.cpp file was part of an exploratory phase where MQTT was tested as a communication protocol. We have since decided to abandon this approach.

The code has been removed from our codebase a few weeks ago and is not present in the latest weekly snapshot on the develop-weekly branch. This ensures that the issue you've identified will not impact any future developments.

We're grateful for your contribution to improving our project's accuracy. Please feel free to verify the removal of the code in the updated branch.

If you need any further information or assistance, don't hesitate to reach out.

Best regards,
Sebastien
